version: "3.8"
services:
  blazorapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./BlazorApp1:/src/BlazorApp1
      - /src/BlazorApp1/node_modules
      - /src/BlazorApp1/obj
      - /src/BlazorApp1/bin
